export const caseStudy = {
  slug: "lnp-mrna-antigen-presentation",
  outputFilename: "lnp-mrna-antigen-presentation.drawio",
  title: "LNP-mediated mRNA delivery and MHC-I antigen presentation",
  pageName: "LNP-mRNA mechanism",
  canvas: { width: 1280, height: 760, background: "#fbfaf5", grid: true },
  brief: {
    audience: "生命科学研究人员、论文读者与科研汇报受众",
    question: "脂质纳米颗粒如何把 mRNA 递送进细胞，并最终形成可被 CD8+ T 细胞识别的 MHC-I 抗原复合物？",
    scope: "从细胞外 LNP 到抗原呈递与 T 细胞激活；省略具体脂质配方、剂量、动力学和组织分布。",
    message: "递送不是终点；内体逃逸、翻译与抗原加工共同决定最终免疫呈递。",
  },
  design: {
    readingOrder: "左 → 右；细胞外 → 胞质；递送 → 翻译 → 加工 → 呈递 → 免疫识别",
    zones: ["Extracellular", "Cell membrane", "Cytosol / secretory pathway"],
    palette: {
      delivery: "橙色",
      mrna_translation: "蓝色",
      antigen_processing: "紫色",
      presentation: "绿色",
      immune_response: "珊瑚红",
      failure_branch: "红色虚线",
    },
    editabilityContract: "文字、步骤、区室、节点、箭头和图例全部使用 draw.io 原生对象；不嵌入栅格图片。",
  },
  reviewFindings: [
    { id: "finding-label", severity: "hard", target: "node-mhc", issue: "初稿标签 MHC-I ? 含不确定标记，无法作为出版终稿。" },
    { id: "finding-route", severity: "hard", target: "edge-vesicle-surface", issue: "呈递到膜表面的主通路误用了虚线和 open arrow，语义像假设路径。" },
    { id: "finding-outcome", severity: "soft", target: "node-activation", issue: "结局节点过窄，CD8+ T-cell activation 标签阅读密度偏高。" },
  ],
  vertices: [
    { id: "zone-extracellular", label: "", shape: "rectangle", x: 34, y: 84, width: 245, height: 590, fill_color: "#f7f1e5", stroke_color: "#c9b98f", stroke_width: 1.5 },
    { id: "zone-cytosol", label: "", shape: "rounded", x: 314, y: 84, width: 930, height: 590, fill_color: "#eef6f3", stroke_color: "#76a498", stroke_width: 1.5 },
    { id: "cell-membrane", label: "", shape: "rectangle", x: 284, y: 84, width: 18, height: 590, fill_color: "#d8b96f", stroke_color: "#a88539", stroke_width: 1.2 },
    { id: "label-extracellular", label: "EXTRACELLULAR", shape: "text", x: 55, y: 104, width: 190, height: 28, font_size: 13, font_style: 1, font_color: "#786945" },
    { id: "label-cytosol", label: "CYTOSOL / SECRETORY PATHWAY", shape: "text", x: 350, y: 104, width: 300, height: 28, font_size: 13, font_style: 1, font_color: "#3e6f65" },

    { id: "step-1", label: "1", shape: "ellipse", x: 55, y: 170, width: 34, height: 34, fill_color: "#d87c4a", stroke_color: "#9f4e27", font_color: "#ffffff", font_size: 15, font_style: 1 },
    { id: "node-lnp", label: "LNP", shape: "ellipse", x: 108, y: 154, width: 108, height: 74, fill_color: "#f4b183", stroke_color: "#b55d30", stroke_width: 2.2, font_size: 18, font_style: 1 },
    { id: "node-mrna-cargo", label: "mRNA cargo", shape: "rounded", x: 122, y: 180, width: 80, height: 24, fill_color: "#d9eaf7", stroke_color: "#5e8fb4", font_size: 11 },
    { id: "node-apoe", label: "ApoE", shape: "rounded", x: 112, y: 260, width: 98, height: 42, fill_color: "#fde1cb", stroke_color: "#b9683e", font_size: 14, font_style: 1 },
    { id: "node-ldlr", label: "LDLR", shape: "rounded", x: 242, y: 256, width: 90, height: 50, fill_color: "#efe3bf", stroke_color: "#987637", font_size: 14, font_style: 1 },

    { id: "step-2", label: "2", shape: "ellipse", x: 342, y: 170, width: 34, height: 34, fill_color: "#d87c4a", stroke_color: "#9f4e27", font_color: "#ffffff", font_size: 15, font_style: 1 },
    { id: "node-endosome", label: "Endosome", shape: "ellipse", x: 395, y: 142, width: 150, height: 96, fill_color: "#f8d7bf", stroke_color: "#bd7148", stroke_width: 2, font_size: 16, font_style: 1 },
    { id: "label-endocytosis", label: "receptor-mediated endocytosis", shape: "text", x: 358, y: 252, width: 220, height: 32, font_size: 12, font_color: "#87543a" },
    { id: "node-lysosome", label: "Lysosomal\ndegradation", shape: "rounded", x: 390, y: 354, width: 160, height: 64, fill_color: "#f7d8d3", stroke_color: "#b45245", font_color: "#7b3028", font_size: 14, dashed: true },

    { id: "step-3", label: "3", shape: "ellipse", x: 595, y: 170, width: 34, height: 34, fill_color: "#d87c4a", stroke_color: "#9f4e27", font_color: "#ffffff", font_size: 15, font_style: 1 },
    { id: "node-ionizable-lipid", label: "Protonated\nionizable lipid", shape: "rounded", x: 650, y: 142, width: 160, height: 78, fill_color: "#f8d7bf", stroke_color: "#bd7148", font_size: 14, font_style: 1 },
    { id: "node-mrna", label: "Released mRNA", shape: "rounded", x: 650, y: 274, width: 160, height: 58, fill_color: "#d9eaf7", stroke_color: "#4e87b3", stroke_width: 2.2, font_size: 15, font_style: 1 },
    { id: "label-escape", label: "endosomal escape", shape: "text", x: 642, y: 230, width: 176, height: 28, font_size: 12, font_color: "#87543a" },

    { id: "step-4", label: "4", shape: "ellipse", x: 858, y: 170, width: 34, height: 34, fill_color: "#4e87b3", stroke_color: "#315f81", font_color: "#ffffff", font_size: 15, font_style: 1 },
    { id: "node-ribosome", label: "Ribosome", shape: "hexagon", x: 920, y: 138, width: 154, height: 72, fill_color: "#c9e1f2", stroke_color: "#4e87b3", font_size: 15, font_style: 1 },
    { id: "node-antigen", label: "Encoded antigen", shape: "rounded", x: 920, y: 270, width: 154, height: 58, fill_color: "#c9e1f2", stroke_color: "#4e87b3", font_size: 15, font_style: 1 },
    { id: "label-translation", label: "translation", shape: "text", x: 930, y: 222, width: 134, height: 28, font_size: 12, font_color: "#315f81" },

    { id: "node-proteasome", label: "Proteasome", shape: "cylinder", x: 866, y: 412, width: 150, height: 70, fill_color: "#ddd3ef", stroke_color: "#71599d", font_size: 14, font_style: 1 },
    { id: "node-peptides", label: "Antigenic peptides", shape: "rounded", x: 1060, y: 416, width: 160, height: 58, fill_color: "#ddd3ef", stroke_color: "#71599d", font_size: 14, font_style: 1 },

    { id: "step-5", label: "5", shape: "ellipse", x: 600, y: 480, width: 34, height: 34, fill_color: "#71599d", stroke_color: "#4d3972", font_color: "#ffffff", font_size: 15, font_style: 1 },
    { id: "node-er", label: "Endoplasmic reticulum", shape: "swimlane", x: 650, y: 500, width: 240, height: 112, fill_color: "#eee9f8", stroke_color: "#71599d", font_size: 14, font_style: 1 },
    { id: "node-tap", label: "TAP", shape: "rounded", x: 676, y: 548, width: 72, height: 40, fill_color: "#ddd3ef", stroke_color: "#71599d", font_size: 13, font_style: 1 },
    { id: "node-mhc", label: "MHC-I ?", shape: "rounded", x: 778, y: 542, width: 88, height: 50, fill_color: "#e8e0f5", stroke_color: "#8a73b1", font_size: 13, dashed: true },
    { id: "node-golgi", label: "Golgi", shape: "rounded", x: 930, y: 528, width: 110, height: 62, fill_color: "#dcebd2", stroke_color: "#5f8d4e", font_size: 14, font_style: 1 },
    { id: "node-vesicle", label: "Transport\nvesicle", shape: "ellipse", x: 1080, y: 520, width: 108, height: 78, fill_color: "#dcebd2", stroke_color: "#5f8d4e", font_size: 13 },

    { id: "step-6", label: "6", shape: "ellipse", x: 1030, y: 632, width: 34, height: 34, fill_color: "#c65f52", stroke_color: "#8d3d34", font_color: "#ffffff", font_size: 15, font_style: 1 },
    { id: "node-surface-complex", label: "Surface MHC-I–peptide", shape: "rounded", x: 1082, y: 620, width: 150, height: 54, fill_color: "#cfe6c5", stroke_color: "#4e7b40", font_size: 13, font_style: 1 },
    { id: "node-cd8", label: "CD8+ T cell", shape: "ellipse", x: 862, y: 632, width: 132, height: 70, fill_color: "#f5cfca", stroke_color: "#b65146", font_size: 14, font_style: 1 },
    { id: "node-activation", label: "T-cell\nactivation", shape: "rounded", x: 684, y: 636, width: 128, height: 58, fill_color: "#f5cfca", stroke_color: "#b65146", font_size: 14, font_style: 1 },

    { id: "legend-title", label: "VISUAL KEY", shape: "text", x: 58, y: 500, width: 150, height: 26, font_size: 12, font_style: 1, font_color: "#50482f" },
    { id: "legend-editable", label: "Editable biological object", shape: "rounded", x: 62, y: 536, width: 184, height: 40, fill_color: "#d9eaf7", stroke_color: "#4e87b3", font_size: 12 },
    { id: "legend-branch", label: "Conditional / failure branch", shape: "rounded", x: 62, y: 590, width: 184, height: 40, fill_color: "#f7d8d3", stroke_color: "#b45245", font_size: 12, dashed: true },
    { id: "scope-note", label: "Conceptual mechanism · not to scale", shape: "text", x: 1010, y: 104, width: 210, height: 28, font_size: 11, font_color: "#60726e" },
  ],
  edges: [
    { id: "edge-lnp-apoe", source: "node-lnp", target: "node-apoe", color: "#b55d30", width: 2, end_arrow: "block" },
    { id: "edge-apoe-ldlr", source: "node-apoe", target: "node-ldlr", color: "#9a7130", width: 2.2, end_arrow: "block" },
    { id: "edge-ldlr-endosome", source: "node-ldlr", target: "node-endosome", color: "#a86b43", width: 2.4, end_arrow: "block" },
    { id: "edge-endosome-ionizable", source: "node-endosome", target: "node-ionizable-lipid", color: "#bd7148", width: 2.4, end_arrow: "block" },
    { id: "edge-endosome-lysosome", label: "escape fails", source: "node-endosome", target: "node-lysosome", color: "#b45245", width: 2, dashed: true, end_arrow: "block" },
    { id: "edge-ionizable-mrna", source: "node-ionizable-lipid", target: "node-mrna", color: "#bd7148", width: 2.4, end_arrow: "block" },
    { id: "edge-mrna-ribosome", source: "node-mrna", target: "node-ribosome", color: "#4e87b3", width: 2.5, end_arrow: "block" },
    { id: "edge-ribosome-antigen", source: "node-ribosome", target: "node-antigen", color: "#4e87b3", width: 2.5, end_arrow: "block" },
    { id: "edge-antigen-proteasome", source: "node-antigen", target: "node-proteasome", color: "#71599d", width: 2.4, end_arrow: "block", curved: true },
    { id: "edge-proteasome-peptides", source: "node-proteasome", target: "node-peptides", color: "#71599d", width: 2.4, end_arrow: "block" },
    { id: "edge-peptides-tap", source: "node-peptides", target: "node-tap", color: "#71599d", width: 2.4, end_arrow: "block", curved: true },
    { id: "edge-tap-mhc", source: "node-tap", target: "node-mhc", color: "#71599d", width: 2.2, end_arrow: "block" },
    { id: "edge-mhc-golgi", source: "node-mhc", target: "node-golgi", color: "#5f8d4e", width: 2.4, end_arrow: "block" },
    { id: "edge-golgi-vesicle", source: "node-golgi", target: "node-vesicle", color: "#5f8d4e", width: 2.4, end_arrow: "block" },
    { id: "edge-vesicle-surface", source: "node-vesicle", target: "node-surface-complex", color: "#6e9a5d", width: 2.2, dashed: true, end_arrow: "open" },
    { id: "edge-surface-cd8", source: "node-surface-complex", target: "node-cd8", color: "#b65146", width: 2.5, end_arrow: "block" },
    { id: "edge-cd8-activation", source: "node-cd8", target: "node-activation", color: "#b65146", width: 2.5, end_arrow: "block" },
    { id: "edge-mrna-proteasome-context", label: "antigen processing", source: "node-antigen", target: "node-peptides", color: "#8a73b1", width: 1.4, dashed: true, curved: true, end_arrow: "none" },
    { id: "edge-surface-activation-context", label: "recognition", source: "node-surface-complex", target: "node-activation", color: "#c65f52", width: 1.4, dashed: true, curved: true, end_arrow: "none" },
  ],
  corrections: [
    {
      id: "node-mhc",
      label: "MHC-I peptide\ncomplex",
      style_updates: { dashed: 0, fillColor: "#cfe6c5", strokeColor: "#4e7b40", fontColor: "#254c1f" },
    },
    {
      id: "edge-vesicle-surface",
      style_updates: { dashed: 0, endArrow: "block", endFill: 1, strokeColor: "#4e7b40", strokeWidth: 2.6 },
    },
    {
      id: "node-activation",
      label: "CD8+ T-cell\nactivation",
      x: 656,
      width: 156,
      style_updates: { fillColor: "#efb8b1", strokeColor: "#9d4339", fontStyle: 1 },
    },
  ],
};
